###
@url_dev=http://localhost:5000/v1/api/

###
POST {{url_dev}}/register
Content-Type: application/json

{
    "username" : "username",
    "password" : "password"
}

###
POST {{url_dev}}/login
Content-Type: application/json

{
    "username" : "username",
    "password" : "password"
}

###
GET http://localhost:5000/v1/api/data


###
POST {{url_dev}}/token
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lIiwiaWF0IjoxNzIxNDU5NjA2LCJleHAiOjE3MjIwNjQ0MDZ9.KB_ci6d9RhoZEk33EcSLK-KjuTk4Vqe-BOV3sCKE-RI